---
name: "pr-issues-project"

on:
  issues:
    types: 
    - opened
    - reopened
  
  pull_request:
    types:
    - opened
    - reopened

jobs:
  linters:
    uses: camptocamp/devops-stack/.github/workflows/pr-issues-project.yaml@main
