---
name: "Terraform Docs"

on:
  pull_request:

jobs:
  terraform-docs:
    uses: camptocamp/devops-stack/.github/workflows/modules-terraform-docs.yaml@master
    with:
      # Specify where which subfolders you want the pipeline to scrape in order to generate documentation.
      # If there is no variant, you can delete this variable or leave an empty string as-is.
      variants: ""
